class Recipe {
  String label;
  String imageUrl;

  int servings;
  List<Ingredient> ingredients;

  Recipe(this.label, this.imageUrl, this.servings, this.ingredients);

  static List<Recipe> samples = [
    Recipe('Rawon', 'assets/rawon.jpeg',
    1,
    [
      Ingredient(500, 'gram', 'Daging sapi'),
      Ingredient(3, 'buah', 'Kluwak'),
      Ingredient(2, 'batang', 'Serai'),
      Ingredient(1, 'ruas', 'Lengkuas'),
      Ingredient(3, 'lembar', 'Daun salam'),
      Ingredient(5, 'lembar', 'Daun jeruk'),
      Ingredient(2, 'batang', 'Daun bawang'),
      Ingredient(2, 'sendok makan', 'Garam'),
    ],
    ),
    Recipe('Rujak Cingur', 'assets/rujak cingur.jpeg',
    1,
    [
      Ingredient(150, 'gram', 'Cingur sapi'),
      Ingredient(100, 'gram', 'Toge'),
      Ingredient(1, 'buah', 'Timun'),
      Ingredient(2, 'kotak', 'Tempe goreng'),
      Ingredient(2, 'kotak', 'Tahu goreng'),
      Ingredient(2, 'buah', 'Lontong'),
      Ingredient(50, 'gram', 'Kacang tanah goreng'),
      Ingredient(2, 'siung', 'Bawang putih'),
      Ingredient(1, 'sendok makan', 'Gula merah'),
      Ingredient(1/2, 'sendok teh', 'Terasi'),
      Ingredient(1/2, 'sendok teh', 'Garam'),
      Ingredient(2, 'sendok makan', 'Petis udang'),
    ],
    ),
    Recipe('Lontong Balap', 'assets/lontong balap.jpeg',
    1,
    [
      Ingredient(2, 'buah', 'Lontong'),
      Ingredient(4, 'kotak', 'Tahu goreng'),
      Ingredient(4, 'buah', 'Lentho goreng'),
      Ingredient(100, 'gram', 'Toge'),
      Ingredient(1.5, 'liter', 'Air matang'),
      Ingredient(200, 'gram', 'Daging sapi'),
      Ingredient(1, 'sendok makan', 'Santan'),
      Ingredient(2, 'batang', 'Daun bawang'),
      Ingredient(3, 'Siung', 'Bawang merah'),
      Ingredient(6, 'siung', 'Bawang putih'),
      Ingredient(2, 'sendok teh', 'Garam'),
    ],
    ),
    Recipe('Pecel Semanggi', 'assets/pecel semanggi.jpeg',
    1,
    [
      Ingredient(4, 'daun', 'Semanggi'),
      Ingredient(100, 'gram', 'Toge'),
      Ingredient(200, 'gram', 'Ubi putih'),
      Ingredient(50, 'gram', 'Kacang tanah goreng'),
      Ingredient(30, 'gram', 'Gula merah'),
      Ingredient(2, 'Siung', 'Bawang merah'),
      Ingredient(4, 'siung', 'Bawang putih'),
      Ingredient(1, 'ruas', 'Kencur'),
      Ingredient(1, 'sendok makan', 'Petis udang'),
      Ingredient(1/2, 'liter', 'Air matang'),
      Ingredient(3, 'biji', 'Cabe rawit'),
    ],
    ),
    Recipe('Lontong Kupang', 'assets/lontong kupang.jpeg',
    1,
    [
      Ingredient(200, 'gram', 'Kupang'),
      Ingredient(1, 'buah', 'Jahe'),
      Ingredient(3, 'lembar', 'Daun salam'),
      Ingredient(6, 'lembar', 'Daun jeruk'),
      Ingredient(1, 'sendok teh', 'Garam'),
      Ingredient(1/4, 'sendok teh', 'Gula'),
      Ingredient(1, 'sendok teh', 'Petis Udang'),
      Ingredient(1.5, 'liter', 'Air matang'),
      Ingredient(6, 'siung', 'Bawang putih'),
    ],
    ),
    Recipe('Tahu Tek', 'assets/tahu tek.jpeg',
    4,
    [
      Ingredient(2, 'kotak', 'Tahu goreng'),
      Ingredient(1, 'butir', 'Telur goreng'),
      Ingredient(1, 'buah', 'Kentang'),
      Ingredient(50, 'gram', 'Toge'),
      Ingredient(2, 'buah', 'Lontong'),
      Ingredient(50, 'gram', 'Kerupuk udang'),
      Ingredient(50, 'gram', 'Kacang tanah goreng'),
      Ingredient(1, 'sendok makan', 'Petis udang'),
      Ingredient(2, 'sendok makan', 'Kecap manis'),
      Ingredient(1, 'sendok teh', 'Garam'),
      Ingredient(1/4, 'liter', 'Air matang'),
      Ingredient(3, 'biji', 'Cabe rawit'),
      Ingredient(4, 'siung', 'Bawang putih'),
    ],
    ),
    Recipe('Soto Ayam', 'assets/soto ayam.jpeg',
    4,
    [
      Ingredient(500, 'gram', 'Ayam'),
      Ingredient(3, 'lembar', 'Daun salam'),
      Ingredient(3, 'lembar', 'Daun jeruk'),
      Ingredient(2, 'ruas', 'Serai'),
      Ingredient(1, 'buah', 'Tomat'),
      Ingredient(6, 'cm', 'Lengkuas'),
      Ingredient(2, 'liter', 'Air matang'),
      Ingredient(2, 'sendok makan', 'Gula'),
      Ingredient(1, 'sendok teh', 'Garam'),
      Ingredient(4, 'buah', 'Kemiri'),
      Ingredient(6, 'siung', 'Bawang putih'),
      Ingredient(4, 'siung', 'Bawang merah'),
    ],
    ),
    Recipe('Bakso Malang', 'assets/bakso malang.jpeg',
    4,
    [
      Ingredient(1, 'kg', 'Daging sapi'),
      Ingredient(1/2, 'kg', 'Ayam'),
      Ingredient(250, 'gram', 'Tepung'),
      Ingredient(1, 'sendok teh', 'Baking powder'),
      Ingredient(1, 'butir', 'Telur'),
      Ingredient(1, 'sendok makan', 'Bawang goreng'),
      Ingredient(5, 'siung', 'Bawang putih'),
      Ingredient(1, 'sendok teh', 'Garam'),
    ],
    ),
    Recipe('Tahu Campur', 'assets/tahu campur.jpeg',
    4,
    [
      Ingredient(1/2, 'kg', 'Tetelan sapi'),
      Ingredient(1/2, 'kg', 'Daging sapi'),
      Ingredient(1/4, 'cup', 'Gula jawa'),
      Ingredient(4, 'liter', 'Air matang'),
      Ingredient(2, 'sendok makan', 'Ketumbar'),
      Ingredient(2, 'ruas', 'Kunyit'),
      Ingredient(2, 'ruas', 'Laos'),
      Ingredient(2, 'ruas', 'Jahe'),
      Ingredient(2, 'buah', 'Lentho goreng'),
      Ingredient(1, 'sendok teh', 'Garam'),
      Ingredient(3, 'kotak', 'Tahu goreng'),
      Ingredient(50, 'gram', 'Toge'),
      Ingredient(2, 'buah', 'Lontong'),
      Ingredient(50, 'gram', 'Kerupuk udang'),
      Ingredient(8, 'siung', 'Bawang putih'),
      Ingredient(6, 'siung', 'Bawang merah'),
    ],
    ),Recipe('Nasi Krawu', 'assets/soto ayam.jpeg',
    4,
    [
      Ingredient(250, 'gram', 'Daging sapi'),
      Ingredient(600, 'ml', 'Air matang'),
      Ingredient(2, 'lembar', 'Daun salam'),
      Ingredient(1, 'ruas', 'Serai'),
      Ingredient(100, 'ml', 'Santan'),
      Ingredient(1, 'cm', 'Lengkuas'),
      Ingredient(1, 'cm', 'Kunyit'),
      Ingredient(1/2, 'sendok makan', 'Ketumbar'),
      Ingredient(3, 'sendok makan', 'Garam'),
      Ingredient(2, 'sendok makan', 'Gula'),
      Ingredient(1, 'sendok makan', 'Gula merah'),
      Ingredient(2, 'buah', 'Kemiri'),
      Ingredient(3, 'siung', 'Bawang putih'),
      Ingredient(6, 'siung', 'Bawang merah'),
      Ingredient(1, 'piring', 'Nasi putih'),
    ],
    ),
  ];
}

class Ingredient {
  double quantity;
  String measure;
  String name;

  Ingredient(this.quantity, this.measure, this.name);
}